"""Conversation memory system: short-term (Redis) and long-term (PostgreSQL)."""

from __future__ import annotations

import json
import logging
from datetime import datetime
from typing import Any, Optional

import redis.asyncio as aioredis
from langchain_core.messages import HumanMessage, SystemMessage
from langchain_google_genai import ChatGoogleGenerativeAI
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.config import settings
from src.db.database import async_session_factory
from src.db.models import DialogueSession

logger = logging.getLogger(__name__)

# Redis key prefix for short-term memory
_STM_PREFIX = "stm:session:"
# Redis key prefix for message list
_MSG_PREFIX = "stm:messages:"
# Default TTL for short-term memory entries (30 minutes)
_DEFAULT_TTL = settings.SESSION_TIMEOUT_MINUTES * 60


class ShortTermMemory:
    """Redis-backed short-term conversation memory.

    Stores recent messages for an active session with automatic TTL expiration.
    """

    def __init__(self, redis_url: Optional[str] = None, ttl: int = _DEFAULT_TTL) -> None:
        self.redis_url = redis_url or settings.REDIS_URL
        self.ttl = ttl
        self._redis: Optional[aioredis.Redis] = None

    async def _get_redis(self) -> aioredis.Redis:
        if self._redis is None:
            self._redis = aioredis.from_url(
                self.redis_url, decode_responses=True
            )
        return self._redis

    async def store_message(
        self, session_id: str, role: str, content: str
    ) -> None:
        """Store a message in short-term memory.

        Args:
            session_id: The conversation session identifier.
            role: Message role, either ``"user"`` or ``"npc"``.
            content: The message text.
        """
        r = await self._get_redis()
        key = f"{_MSG_PREFIX}{session_id}"

        message_data = json.dumps(
            {"role": role, "content": content, "timestamp": datetime.utcnow().isoformat()},
            ensure_ascii=False,
        )

        await r.rpush(key, message_data)
        await r.expire(key, self.ttl)

    async def get_history(
        self, session_id: str, limit: int = 20
    ) -> list[dict[str, str]]:
        """Get recent message history for a session.

        Args:
            session_id: The conversation session identifier.
            limit: Maximum number of messages to return.

        Returns:
            List of message dicts with ``role`` and ``content`` keys,
            ordered from oldest to newest.
        """
        r = await self._get_redis()
        key = f"{_MSG_PREFIX}{session_id}"

        raw_messages = await r.lrange(key, -limit, -1)
        messages: list[dict[str, str]] = []
        for raw in raw_messages:
            try:
                msg = json.loads(raw)
                messages.append({"role": msg["role"], "content": msg["content"]})
            except (json.JSONDecodeError, KeyError):
                continue

        return messages

    async def get_recent_context(
        self, session_id: str, turns: int = 3
    ) -> str:
        """Get a formatted string of recent turns for intent classification context.

        Args:
            session_id: The conversation session identifier.
            turns: Number of recent message pairs to include.

        Returns:
            Formatted string of recent conversation turns.
        """
        messages = await self.get_history(session_id, limit=turns * 2)
        if not messages:
            return ""

        parts: list[str] = []
        for msg in messages:
            role_label = "유저" if msg["role"] == "user" else "NPC"
            parts.append(f"{role_label}: {msg['content']}")

        return "\n".join(parts)

    async def clear(self, session_id: str) -> None:
        """Clear all short-term memory for a session.

        Args:
            session_id: The conversation session identifier.
        """
        r = await self._get_redis()
        key = f"{_MSG_PREFIX}{session_id}"
        await r.delete(key)

    async def close(self) -> None:
        """Close the Redis connection."""
        if self._redis is not None:
            await self._redis.close()
            self._redis = None


class LongTermMemory:
    """PostgreSQL-backed long-term conversation memory.

    Stores session summaries generated by LLM for persistent context
    across sessions.
    """

    async def save_summary(
        self,
        user_id: str,
        npc_id: str,
        session_id: str,
        summary: str,
    ) -> None:
        """Save a session summary to the database.

        Args:
            user_id: The user identifier (UUID string).
            npc_id: The NPC identifier (UUID string).
            session_id: The session identifier (UUID string).
            summary: LLM-generated summary of the conversation.
        """
        async with async_session_factory() as session:
            stmt = (
                select(DialogueSession)
                .where(DialogueSession.id == session_id)
            )
            result = await session.execute(stmt)
            dialogue_session = result.scalar_one_or_none()

            if dialogue_session is not None:
                dialogue_session.summary = summary
                dialogue_session.ended_at = datetime.utcnow()
                await session.commit()
                logger.info(
                    "Saved session summary for session=%s user=%s npc=%s",
                    session_id, user_id, npc_id,
                )
            else:
                logger.warning(
                    "Session %s not found when saving summary", session_id
                )

    async def get_summaries(
        self,
        user_id: str,
        npc_id: str,
        limit: int = 3,
    ) -> list[str]:
        """Get recent session summaries for a user-NPC pair.

        Args:
            user_id: The user identifier (UUID string).
            npc_id: The NPC identifier (UUID string).
            limit: Maximum number of summaries to return.

        Returns:
            List of summary strings, newest first.
        """
        async with async_session_factory() as session:
            stmt = (
                select(DialogueSession.summary)
                .where(
                    DialogueSession.user_id == user_id,
                    DialogueSession.npc_id == npc_id,
                    DialogueSession.summary.isnot(None),
                )
                .order_by(DialogueSession.ended_at.desc())
                .limit(limit)
            )
            result = await session.execute(stmt)
            rows = result.scalars().all()
            return [s for s in rows if s]

    async def get_cross_npc_summaries(
        self,
        user_id: str,
        related_npc_ids: list[str],
        limit: int = 2,
    ) -> list[str]:
        """Get session summaries from related NPCs for cross-NPC memory.

        Allows an NPC to reference information the player discussed with
        other connected NPCs (e.g., an NPC knowing the player already
        talked to another NPC in the same quest chain).

        Args:
            user_id: The user identifier (UUID string).
            related_npc_ids: List of related NPC identifiers (UUID strings).
            limit: Maximum number of summaries per NPC.

        Returns:
            List of summary strings from related NPC conversations.
        """
        if not related_npc_ids:
            return []

        async with async_session_factory() as session:
            stmt = (
                select(DialogueSession.summary)
                .where(
                    DialogueSession.user_id == user_id,
                    DialogueSession.npc_id.in_(related_npc_ids),
                    DialogueSession.summary.isnot(None),
                )
                .order_by(DialogueSession.ended_at.desc())
                .limit(limit)
            )
            result = await session.execute(stmt)
            rows = result.scalars().all()
            return [s for s in rows if s]


SUMMARIZATION_PROMPT = """다음은 유저와 NPC의 대화 기록입니다. 이 대화를 3-5문장으로 요약하세요.
중요한 정보, 감정 변화, 퀘스트 관련 내용을 포함하세요.

대화 기록:
{conversation}

요약:"""


class MemoryManager:
    """Combines short-term and long-term memory for the dialogue pipeline.

    Orchestrates memory retrieval for prompt construction and triggers
    LLM-based summarization when a session ends.
    """

    def __init__(
        self,
        short_term: Optional[ShortTermMemory] = None,
        long_term: Optional[LongTermMemory] = None,
    ) -> None:
        self.short_term = short_term or ShortTermMemory()
        self.long_term = long_term or LongTermMemory()
        self._llm: Optional[ChatGoogleGenerativeAI] = None

    @property
    def llm(self) -> ChatGoogleGenerativeAI:
        if self._llm is None:
            self._llm = ChatGoogleGenerativeAI(
                model=settings.LLM_MODEL,
                google_api_key=settings.GEMINI_API_KEY,
                temperature=0.3,
            )
        return self._llm

    async def on_session_end(
        self,
        session_id: str,
        user_id: str,
        npc_id: str,
    ) -> Optional[str]:
        """Trigger LLM summarization of the session and save to long-term memory.

        Called when a WebSocket disconnects or a session times out.

        Args:
            session_id: The conversation session identifier.
            user_id: The user identifier.
            npc_id: The NPC identifier.

        Returns:
            The generated summary string, or ``None`` if no messages existed.
        """
        messages = await self.short_term.get_history(session_id, limit=100)
        if not messages:
            return None

        # Format conversation for summarization
        conversation_text = "\n".join(
            f"{'유저' if m['role'] == 'user' else 'NPC'}: {m['content']}"
            for m in messages
        )

        prompt = SUMMARIZATION_PROMPT.format(conversation=conversation_text)

        try:
            response = await self.llm.ainvoke(
                [
                    SystemMessage(content="당신은 대화 요약 전문가입니다."),
                    HumanMessage(content=prompt),
                ]
            )
            summary = response.content.strip()
        except Exception as e:
            logger.error("Session summarization failed: %s", e)
            # Fallback: use first and last messages as a rough summary
            first = messages[0]["content"][:100]
            last = messages[-1]["content"][:100]
            summary = f"대화 시작: {first}... / 대화 종료: {last}..."

        await self.long_term.save_summary(user_id, npc_id, session_id, summary)
        await self.short_term.clear(session_id)

        logger.info("Session %s summarized and archived.", session_id)
        return summary

    async def get_context_for_prompt(
        self,
        user_id: str,
        npc_id: str,
        session_id: str,
    ) -> dict[str, str]:
        """Retrieve both short-term and long-term memory for prompt construction.

        Args:
            user_id: The user identifier.
            npc_id: The NPC identifier.
            session_id: The current session identifier.

        Returns:
            Dictionary with ``short_term_memory`` and ``long_term_memory`` keys.
        """
        # Short-term: recent messages from the current session
        short_term_context = await self.short_term.get_recent_context(
            session_id, turns=3
        )

        # Long-term: past session summaries
        summaries = await self.long_term.get_summaries(user_id, npc_id, limit=3)
        long_term_context = "\n---\n".join(summaries) if summaries else ""

        return {
            "short_term_memory": short_term_context,
            "long_term_memory": long_term_context,
        }

    async def close(self) -> None:
        """Release resources."""
        await self.short_term.close()
